version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /etc/ssl/certs/certificate.crt:/etc/ssl/certificate.crt:ro
      - /etc/ssl/certs/ca_bundle.crt:/etc/ssl/ca_bundle.crt:ro
      - /etc/ssl/private/private.key:/etc/ssl/private.key:ro
      - ./nginx_logs:/var/log/nginx
    
    depends_on:
      - web
    networks:
      - app-network
  
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres-data:
  static_volume:
  media_volume:
  nginx_logs:
