products = [
    {
        "_id": '1',
        "title": "Clorador salino",
        "subtitle": "Olvidate de comprar mas cloro. Venta y puesta en marcha de todo el sistema.",
        "description": "Este hecho te facilitará muchísimo sustituir un tratamiento tradicional de cloro.Cuando el agua salada de nuestra piscina pasa a través del clorador. La sal disuelta se transforma en hipoclorito sódico (NaCIO) que disuelto en agua, resulta un potente desinfectante. Además, la célula generará automáticamente un cloro libre (Cl2) que no se degrada.El potente desinfectante que crean mediante su proceso de descomposición, iones de cloruro, elimina las sustancias contaminantes que aparecen en el agua (bacterias, algas, cloraminas, etc)",
        "img": "/images/clorador.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 3.5,
        'numReviews': 30,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '2',
        "title": "Bomba peristáltica",
        "subtitle": "La solución mas duradera y económica. Venta y cambio de la pieza, presupuesto sin compromiso",
        "description": "Una bomba peristáltica es un tipo de bomba hidráulica de desplazamiento positivo usada para bombear una variedad de fluidos. Mientras que el rotor da vuelta, la parte del tubo bajo compresión se cierra (o se ocluye) forzando, de esta manera, el fluido a ser bombeado para moverse a través del tubo. Adicionalmente, mientras el tubo se vuelve a abrir a su estado natural después del paso de la leva ('restitución'), el flujo del fluido es inducido a la bomba. Este proceso es llamado peristalsis y es usado en muchos sistemas biológicos como el aparato digestivo.",
        "img": "/images/Bomba-peristaltica.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 1.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '3',
        "title": "Valvula Selectora",
        "subtitle": "Venta y cambio de la pieza, presupuesto sin compromiso",
        "description": "La gama de válvulas selectoras AstralPool están diseñadas pensando en el usuario que tiene que manipularlas. De innovador diseño, cómodo manejo y máxima ﬁabil_idad, éstas se convierten en un elemento básico en el éxito del perfecto estado de su piscina.",
        "img": "/images/valvula_selectora.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 4.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '4',
        "title": "Tricomplet Granulado",
        "subtitle": "Venta y entrega a domicilio a particulares o empresas",
        "description": "Ahora tiempo y dinero con este producto que contiene Cloro, Algic_ida y floculante.",
        "img": "/images/tricomplet.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 4.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '5',
        "title": "Alkaliplus",
        "subtitle": "Tu mayor aliado para ahorrar cloro",
        "description": "Con una buena regulación de la alcalin_idad del agua podemos mantener el pH en sus margenes y por lo tanto una reducción del consumo de cloro.",
        "img": "/images/alkaliplus.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 4.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '6',
        "title": "Riego Automático RAIN BIRD",
        "subtitle": "La marca con mayor fiabil_idad del mercado",
        "description": "Relajate en tu jardin y deja que la tecnologia Rain Bird se encargue del riego de todo tu patio. Preuspuesto y puesta en marcha de todo el sistema.",
        "img": "/images/riegoAuto.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 4.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '7',
        "title": "Motor para piscina",
        "subtitle": "Trabajamos con la mejor marca del mercado, por que al final lo barato sale caro.",
        "description": "Si se rompe tu motor el agua de la pisicina se pone verde y turbia. Tenemos motores en stock y ademas te incluimos el cambio de motor en 1 o dos dias habiles.",
        "img": "/images/motor.JPG",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 3,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '8',
        "title": "Focos Led para piscina y exteriores",
        "subtitle": "Dale v_ida nocturna a tu piscina y patio",
        "description": "No hay nada mejor que una buena iluminación para disfrutar de tu preciosa piscina y exteriores. Con la tecnologia LED ahorras dinero en la factura de la luz.",
        "img": "/images/foco.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 4.5,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 10,
    }, {
        "_id": '9',
        "title": "Limpia Fondos",
        "subtitle": "Perfecto para todo tipo de piscinas",
        "description": "Este modelo es perfecto para todo tipo de piscinas. Las piscinas de liner son dificiles de limpiar el fondo y este diseño esta pensado para resolver ese molesto problema.",
        "img": "/images/limpiaFondo.jpg",
        "leftColor": "#68b38400",
        "rightColor": "#74c0c62b",
        'rating': 2,
        'numReviews': 12,
        'price': 89.99,
        'countInStock': 0,
    },
]
